apiVersion: solr.apache.org/v1beta1
kind: SolrCloud
metadata:
  name: {{ include "solr.fullname" . }}
  labels:
    {{- include "solr.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.solr.replicas }}
  dataStorage:
    persistent:
      reclaimPolicy: Delete
      pvcTemplate:
        spec:
          resources:
            requests:
              storage: "{{ .Values.solr.storage.size }}"
  solrImage:
    tag: "{{ default .Chart.AppVersion .Values.solr.tag }}"
  solrJavaMem: "{{ .Values.solr.solrJavaMem }}"
  solrSecurity:
    authenticationType: Basic
    probesRequireAuth: true
    basicAuthSecret: {{ .Values.solr.basicAuthSecret }}
  {{- if .Values.solr.customSolrKubeOptions }}
  customSolrKubeOptions:
    {{- toYaml .Values.solr.customSolrKubeOptions | nindent 4 }}
  {{- end }}
  zookeeperRef:
    provided:
      chroot: "/this/will/be/auto/created"
      persistence:
        spec:
          storageClassName: "default"
          resources:
            requests:
              storage: "{{ .Values.zookeeper.storage.size }}"
      replicas: {{ .Values.zookeeper.replicas }}
      {{- if .Values.zookeeper.resources }}
      zookeeperPodPolicy:
        resources:
          {{- toYaml .Values.zookeeper.resources | nindent 10 }}
      {{- end }}
  solrOpts: "-Dsolr.autoSoftCommit.maxTime=10000"
  solrGCTune: "-XX:SurvivorRatio=4 -XX:TargetSurvivorRatio=90 -XX:MaxTenuringThreshold=8"
