{{- if and .Values.drupal.backup.persistence.enabled (not .Values.drupal.backup.persistence.existingClaim) -}}
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  {{- if .Values.drupal.backup.persistence.annotations }}
  annotations:
    {{- toYaml .Values.drupal.backup.persistence.annotations | nindent 4 }}
  {{- end }}
  name: {{ include "drupal.fullname" . }}-drupal-backup
  labels:
    app.kubernetes.io/name: {{ include "drupal.name" . }}-drupal-backup
    helm.sh/chart: {{ include "drupal.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
spec:
  accessModes:
    - {{ .Values.drupal.backup.persistence.accessMode | quote }}
  resources:
    requests:
      storage: {{ .Values.drupal.backup.persistence.size | quote }}
      {{- if .Values.drupal.backup.persistence.iops }}
      iops: {{ .Values.drupal.backup.persistence.iops | quote }}
      {{- end }}
  {{- if .Values.drupal.backup.persistence.storageClass }}
  {{- if (eq "-" .Values.drupal.backup.persistence.storageClass) }}
  storageClassName: ""
  {{- else }}
  storageClassName: "{{ .Values.drupal.backup.persistence.storageClass }}"
  {{- end }}
  {{- end }}
{{- end }}
